# Generated by Django 6.0.7 on 2026-08-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_customcakerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakerequest',
            name='quoted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
