# Generated by Django 6.0.7 on 2026-09-07 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_customcakerequest_quoted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcakerequest',
            name='description',
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='colour_theme',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='custom_message',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='filling',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='flavour',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='frosting_style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='occasion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='servings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='special_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='tier_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customcakerequest',
            name='toppings',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='CustomCakeReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom_cake_references/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='menu.customcakerequest')),
            ],
        ),
    ]
