"""
Django settings for bakery_backend project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

def _split(value):
    return [item.strip() for item in value.split(',') if item.strip()]


ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='127.0.0.1,localhost',
    cast=_split,
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'corsheaders',
    'users',
    'menu',
    'staff',
    'orders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bakery_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bakery_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL'),
        conn_max_age=600,
        # Managed Postgres (Neon, Supabase, Railway, RDS, …) requires SSL.
        # A Postgres container on the same private network as this app — e.g.
        # a database created inside Dokploy — usually has none, and the
        # connection then fails with "server does not support SSL". Set
        # DATABASE_SSL=False in that case.
        ssl_require=config('DATABASE_SSL', default=True, cast=bool),
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# The bakery and every customer are in Kenya. USE_TZ still stores all
# datetimes as UTC in the database — this only sets how "local" is
# interpreted, which matters for timezone.localdate(): it decides which
# day staff stock/sales get filed under, the earliest date an order can
# be placed for, and which dates the blocked-date calendar treats as past.
# At UTC those all roll over at 3am Nairobi. (tzdata is in requirements.)
TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}


AUTH_USER_MODEL = 'users.User'

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://127.0.0.1:8000,http://localhost:8000',
    cast=_split,
)


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}


# Configure Token Lifetimes according to the security guide
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),   # Short-lived token used for API requests
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),      # Long-lived token used to get a new access token
    'ROTATE_REFRESH_TOKENS': True,                    # Issues a brand new refresh token whenever one is used
    'BLACKLIST_AFTER_ROTATION': True,                 # Immediately blacklists the old refresh token so it cannot be reused

}


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email (order confirmations, status updates — see orders/emails.py and
# menu/emails.py). Falls back to printing emails to the console when no
# EMAIL_HOST is configured, so local dev and CI never need real credentials.
EMAIL_HOST = config('EMAIL_HOST', default='')
EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
    if EMAIL_HOST
    else 'django.core.mail.backends.console.EmailBackend'
)
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default="Lizzy's Bakery <noreply@lizzysbakery.com>")

# Used to build the password reset link emailed to the user (users/emails.py)
# — must point at the real frontend domain in production.
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')

# PRD 2.1: reset links expire after 30 minutes. Applies to Django's
# default_token_generator, used by users/serializers.py.
PASSWORD_RESET_TIMEOUT = 60 * 30


# CORS Configurations
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:5173,http://localhost:5174,http://127.0.0.1:5173,http://127.0.0.1:5174',
    cast=_split,
)

# Prevent Django from crashing or redirecting POST requests that lack a trailing slash
APPEND_SLASH = False

CORS_ALLOW_CREDENTIALS = True

# django-cors-headers only allows its own default header set unless told
# otherwise — X-Staff-Token (the staff kiosk's auth header) isn't in it,
# so every staff API call would fail CORS preflight without this.
from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + ['x-staff-token']

